"""Add pitch table and its columns

Revision ID: 04e9ff6d843d
Revises: 6e78365094b8
Create Date: 2020-02-09 23:39:16.873579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04e9ff6d843d'
down_revision = '6e78365094b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pitches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('pitch', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('posted', sa.DateTime(), nullable=True),
    sa.Column('upvote', sa.Integer(), nullable=True),
    sa.Column('downvote', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('pitch_users', sa.Column('user_pitch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pitch_users', 'pitches', ['user_pitch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pitch_users', type_='foreignkey')
    op.drop_column('pitch_users', 'user_pitch_id')
    op.drop_table('pitches')
    # ### end Alembic commands ###
