"""Add comment section

Revision ID: 2bed0cd67fc4
Revises: 7f2c0568d9e6
Create Date: 2020-02-11 12:19:14.051354

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2bed0cd67fc4'
down_revision = '7f2c0568d9e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('user_comment', sa.Integer(), nullable=True),
    sa.Column('user_pitch', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_comment'], ['pitch_users.id'], ),
    sa.ForeignKeyConstraint(['user_pitch'], ['pitches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('pitches', sa.Column('posted_at', sa.DateTime(), nullable=True))
    op.drop_column('pitches', 'posted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('posted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'posted_at')
    op.drop_table('comments')
    # ### end Alembic commands ###
