"""Create email,bio,profile pic path columns

Revision ID: 6e78365094b8
Revises: c27b7888a4fb
Create Date: 2020-02-09 18:22:02.726748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e78365094b8'
down_revision = 'c27b7888a4fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch_users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('pitch_users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('pitch_users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    op.add_column('pitch_users', sa.Column('user_password', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_pitch_users_email'), 'pitch_users', ['email'], unique=True)
    op.create_index(op.f('ix_pitch_users_username'), 'pitch_users', ['username'], unique=False)
    op.drop_column('pitch_users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch_users', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_pitch_users_username'), table_name='pitch_users')
    op.drop_index(op.f('ix_pitch_users_email'), table_name='pitch_users')
    op.drop_column('pitch_users', 'user_password')
    op.drop_column('pitch_users', 'profile_pic_path')
    op.drop_column('pitch_users', 'email')
    op.drop_column('pitch_users', 'bio')
    # ### end Alembic commands ###
