"""Change the Database schema

Revision ID: 7f2c0568d9e6
Revises: 04e9ff6d843d
Create Date: 2020-02-10 12:09:59.265031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f2c0568d9e6'
down_revision = '04e9ff6d843d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pitch_users_user_pitch_id_fkey', 'pitch_users', type_='foreignkey')
    op.drop_column('pitch_users', 'user_pitch_id')
    op.add_column('pitches', sa.Column('user_pitch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pitches', 'pitch_users', ['user_pitch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.drop_column('pitches', 'user_pitch_id')
    op.add_column('pitch_users', sa.Column('user_pitch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('pitch_users_user_pitch_id_fkey', 'pitch_users', 'pitches', ['user_pitch_id'], ['id'])
    # ### end Alembic commands ###
