"""Initial Migration

Revision ID: e0cfcb59f5d8
Revises: 
Create Date: 2020-02-09 12:56:34.103105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0cfcb59f5d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_rights', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pitch_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('user_right_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_right_id'], ['rights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pitch_users')
    op.drop_table('rights')
    # ### end Alembic commands ###
